# Generated by Django 5.0.6 on 2024-06-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_todo_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['pk']},
        ),
    ]
