# Generated by Django 5.0.6 on 2024-07-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0005_alter_todo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task',
        ),
        migrations.AddField(
            model_name='todo',
            name='task_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
